server:
  port: 8081

spring:
  flyway:
    enabled: true
    location: classpath:db/migration
    flyway_schema_history: table_history
    baselineOnMigrate: true

  datasource:
    url: jdbc:postgresql://localhost:5432/commande_db
    username: admin
    password: admin
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/Commande_realm
          jwk-set-uri: http://localhost:8080/realms/Commande_realm/protocol/openid-connect/certs
