package com.commande.webapp.entity;
// Generated 25 oct. 2024, 20 h 45 min 55 s by Hibernate Tools 6.2.6.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import java.util.HashSet;
import java.util.Set;

/**
 * Client generated by hbm2java
 */
@Entity
@Table(name="client",schema="public")
public class Client  implements java.io.Serializable {


     private String id;
     private String nom;
     private String prenom;
     private String adresse;
     private String telephone;
     private Set commandes = new HashSet(0);

    public Client() {
    }

    public Client(String id, String nom, String prenom, String adresse, String telephone, Set commandes) {
       this.id = id;
       this.nom = nom;
       this.prenom = prenom;
       this.adresse = adresse;
       this.telephone = telephone;
       this.commandes = commandes;
    }
   
    @Id
    @Column(name="id", unique=true, nullable=false, length=36)
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }

    
    @Column(name="nom", nullable=false, length=50)
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }

    
    @Column(name="prenom", nullable=false, length=50)
    public String getPrenom() {
        return this.prenom;
    }
    
    public void setPrenom(String prenom) {
        this.prenom = prenom;
    }

    
    @Column(name="adresse", nullable=false, length=100)
    public String getAdresse() {
        return this.adresse;
    }
    
    public void setAdresse(String adresse) {
        this.adresse = adresse;
    }

    
    @Column(name="telephone", nullable=false, length=13)
    public String getTelephone() {
        return this.telephone;
    }
    
    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }

    @OneToMany(fetch=FetchType.LAZY, mappedBy="client", targetEntity = Commande.class)
    public Set getCommandes() {
        return this.commandes;
    }
    
    public void setCommandes(Set commandes) {
        this.commandes = commandes;
    }




}


