package com.commande.webapp.entity;
// Generated 25 oct. 2024, 20 h 45 min 55 s by Hibernate Tools 6.2.6.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import java.util.HashSet;
import java.util.Set;

/**
 * Commande generated by hbm2java
 */
@Entity
@Table(name="commande",schema="public")
public class Commande  implements java.io.Serializable {


     private String id;
     private Client client;
     private String dateCommande;
     private String adresseLivraison;
     private Set commandeItems = new HashSet(0);

    public Commande() {
    }

    public Commande(String id, Client client, String dateCommande, String adresseLivraison, Set commandeItems) {
       this.id = id;
       this.client = client;
       this.dateCommande = dateCommande;
       this.adresseLivraison = adresseLivraison;
       this.commandeItems = commandeItems;
    }
   
    @Id
    @Column(name="id", unique=true, nullable=false, length=36)
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }

    @ManyToOne(fetch=FetchType.LAZY, targetEntity = Client.class)
    @JoinColumn(name="id_client", nullable=false)
    public Client getClient() {
        return this.client;
    }
    
    public void setClient(Client client) {
        this.client = client;
    }

    
    @Column(name="date_commande", nullable=false, length=20)
    public String getDateCommande() {
        return this.dateCommande;
    }
    
    public void setDateCommande(String dateCommande) {
        this.dateCommande = dateCommande;
    }

    
    @Column(name="adresse_livraison", nullable=false, length=100)
    public String getAdresseLivraison() {
        return this.adresseLivraison;
    }
    
    public void setAdresseLivraison(String adresseLivraison) {
        this.adresseLivraison = adresseLivraison;
    }

    @OneToMany(fetch=FetchType.LAZY, mappedBy="commande", targetEntity = CommandeItem.class)
    public Set getCommandeItems() {
        return this.commandeItems;
    }
    
    public void setCommandeItems(Set commandeItems) {
        this.commandeItems = commandeItems;
    }




}


