package com.commande.webapp.entity;
// Generated 25 oct. 2024, 20 h 45 min 55 s by Hibernate Tools 6.2.6.Final


import jakarta.persistence.Column;
import jakarta.persistence.Embeddable;

/**
 * CommandeItemId generated by hbm2java
 */
@Embeddable
public class CommandeItemId  implements java.io.Serializable {


     private String idCommande;
     private String idProduit;
     private int quantite;

    public CommandeItemId() {
    }

    public CommandeItemId(String idCommande, String idProduit, int quantite) {
       this.idCommande = idCommande;
       this.idProduit = idProduit;
       this.quantite = quantite;
    }
   


    @Column(name="id_commande", nullable=false, length=36)
    public String getIdCommande() {
        return this.idCommande;
    }
    
    public void setIdCommande(String idCommande) {
        this.idCommande = idCommande;
    }


    @Column(name="id_produit", nullable=false, length=36)
    public String getIdProduit() {
        return this.idProduit;
    }
    
    public void setIdProduit(String idProduit) {
        this.idProduit = idProduit;
    }


    @Column(name="quantite", nullable=false)
    public int getQuantite() {
        return this.quantite;
    }
    
    public void setQuantite(int quantite) {
        this.quantite = quantite;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof CommandeItemId) ) return false;
		 CommandeItemId castOther = ( CommandeItemId ) other; 
         
		 return ( (this.getIdCommande()==castOther.getIdCommande()) || ( this.getIdCommande()!=null && castOther.getIdCommande()!=null && this.getIdCommande().equals(castOther.getIdCommande()) ) )
 && ( (this.getIdProduit()==castOther.getIdProduit()) || ( this.getIdProduit()!=null && castOther.getIdProduit()!=null && this.getIdProduit().equals(castOther.getIdProduit()) ) )
 && (this.getQuantite()==castOther.getQuantite());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getIdCommande() == null ? 0 : this.getIdCommande().hashCode() );
         result = 37 * result + ( getIdProduit() == null ? 0 : this.getIdProduit().hashCode() );
         result = 37 * result + this.getQuantite();
         return result;
   }   


}


