package com.commande.webapp.entity;
// Generated 25 oct. 2024, 20 h 45 min 55 s by Hibernate Tools 6.2.6.Final


import jakarta.persistence.AttributeOverride;
import jakarta.persistence.AttributeOverrides;
import jakarta.persistence.Column;
import jakarta.persistence.EmbeddedId;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;

/**
 * CommandeItem generated by hbm2java
 */
@Entity
@Table(name="commande_item",schema="public")
public class CommandeItem  implements java.io.Serializable {


     private CommandeItemId id;
     private Commande commande;
     private Produit produit;

    public CommandeItem() {
    }

    public CommandeItem(CommandeItemId id, Commande commande, Produit produit) {
       this.id = id;
       this.commande = commande;
       this.produit = produit;
    }
   
    @EmbeddedId
    @AttributeOverrides( {
        @AttributeOverride(name="idCommande", column=@Column(name="id_commande", nullable=false, length=36) ), 
        @AttributeOverride(name="idProduit", column=@Column(name="id_produit", nullable=false, length=36) ), 
        @AttributeOverride(name="quantite", column=@Column(name="quantite", nullable=false) ) } )
    public CommandeItemId getId() {
        return this.id;
    }
    
    public void setId(CommandeItemId id) {
        this.id = id;
    }

    @ManyToOne(fetch=FetchType.LAZY, targetEntity = Commande.class)
    @JoinColumn(name="id_commande", nullable=false, insertable=false, updatable=false)
    public Commande getCommande() {
        return this.commande;
    }
    
    public void setCommande(Commande commande) {
        this.commande = commande;
    }

    @ManyToOne(fetch=FetchType.LAZY, targetEntity = Produit.class)
    @JoinColumn(name="id_produit", nullable=false, insertable=false, updatable=false)
    public Produit getProduit() {
        return this.produit;
    }
    
    public void setProduit(Produit produit) {
        this.produit = produit;
    }




}


