package com.commande.webapp.entity;
// Generated 25 oct. 2024, 20 h 45 min 55 s by Hibernate Tools 6.2.6.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import java.util.HashSet;
import java.util.Set;

/**
 * Produit generated by hbm2java
 */
@Entity
@Table(name="produit",schema="public")
public class Produit  implements java.io.Serializable {


     private String id;
     private String libelle;
     private String packaging;
     private byte poids;
     private String unite;
     private Set commandeItems = new HashSet(0);

    public Produit() {
    }

    public Produit(String id, String libelle, String packaging, byte poids, String unite, Set commandeItems) {
       this.id = id;
       this.libelle = libelle;
       this.packaging = packaging;
       this.poids = poids;
       this.unite = unite;
       this.commandeItems = commandeItems;
    }
   
    @Id
    @Column(name="id", unique=true, nullable=false, length=36)
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }

    
    @Column(name="libelle", nullable=false, length=100)
    public String getLibelle() {
        return this.libelle;
    }
    
    public void setLibelle(String libelle) {
        this.libelle = libelle;
    }

    
    @Column(name="packaging", nullable=false, length=30)
    public String getPackaging() {
        return this.packaging;
    }
    
    public void setPackaging(String packaging) {
        this.packaging = packaging;
    }

    
    @Column(name="poids", nullable=false, precision=0, scale=0)
    public byte getPoids() {
        return this.poids;
    }
    
    public void setPoids(byte poids) {
        this.poids = poids;
    }

    
    @Column(name="unite", nullable=false, length=2)
    public String getUnite() {
        return this.unite;
    }
    
    public void setUnite(String unite) {
        this.unite = unite;
    }

    @OneToMany(fetch=FetchType.LAZY, mappedBy="produit", targetEntity = CommandeItem.class)
    public Set getCommandeItems() {
        return this.commandeItems;
    }
    
    public void setCommandeItems(Set commandeItems) {
        this.commandeItems = commandeItems;
    }




}


